#!/data/data/com.termux/files/usr/bin/bash

if ! command -v python &> /dev/null; then
    echo "Python 未安装，正在安装..."
    # 安装 Python
    pkg install python -y
    if [ $? -ne 0 ]; then
        echo "Python 安装失败"
        exit 1
    fi
    echo "Python 安装完成。"
else
    echo "Python 已安装。"
fi

# 确保脚本具有可执行权限
chmod 777 ue

# 运行 Python 脚本
python 0
